DROP SCHEMA IF exists toAnunciando CASCADE;
CREATE SCHEMA toAnunciando;

CREATE TABLE ANUNCIANTES (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    "CPF/CNPJ" VARCHAR(14) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    ENDERECO VARCHAR(100) NOT NULL,
    CIDADE VARCHAR(40) NOT NULL,
    UF VARCHAR(2) NOT NULL,
    PAIS VARCHAR(2) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    CREDITOS INTEGER 
);

CREATE TABLE IMOVEIS (
    ID SERIAL PRIMARY KEY,
    ID_ANUNCIANTE INTEGER NOT NULL,
    DESCRICAO VARCHAR(100) NOT NULL,
    OBSERVACAO TEXT,
    TIPO_IMOVEL VARCHAR(1) NOT NULL,
    TIPO_NEGOCIO VARCHAR(1) NOT NULL,
    VALOR NUMERIC(15, 2) NOT NULL,
    ENDERECO VARCHAR(100) NOT NULL,
    CIDADE VARCHAR(40) NOT NULL,
    UF VARCHAR(2) NOT NULL,
    PAIS VARCHAR(2) NOT NULL,
    AREA_PRIVATIVA NUMERIC(15, 2),
    AREA_CONSTRUIDA NUMERIC(15, 2),
    AREA_EXTERNA NUMERIC(15, 2),
    AREA_TOTAL NUMERIC(15, 2),
    CONSTRAINT fk_anunciante FOREIGN KEY (ID_ANUNCIANTE) REFERENCES ANUNCIANTES(ID)
);

-- Adicionando comentários para documentação
COMMENT ON COLUMN IMOVEIS.TIPO_IMOVEL IS 'Tipo do imóvel: C-Casa; A-Apartamento; L-Lote; T-Terreno';
COMMENT ON COLUMN IMOVEIS.TIPO_NEGOCIO IS 'Tipo de negócio: A-Aluguel; V-Venda; T-Troca';

CREATE TABLE CARROS (
    ID SERIAL PRIMARY KEY,
    ID_ANUNCIANTE INTEGER NOT NULL,
    DESCRICAO VARCHAR(100) NOT NULL,
    OBSERVACAO TEXT,
    VALOR NUMERIC(15, 2) NOT NULL,
    CIDADE VARCHAR(40) NOT NULL,
    UF VARCHAR(2) NOT NULL,
    PAIS VARCHAR(2) NOT NULL,
    ANO_FABRICACAO VARCHAR(9) NOT NULL,
    KM INTEGER NOT NULL,
    PLACA VARCHAR(8) NOT NULL,
    MARCA VARCHAR(20) NOT NULL,
    TIPO_MODELO VARCHAR(1) NOT NULL,
    COMBUSTIVEL VARCHAR(1) NOT NULL,
    COR VARCHAR(20) NOT NULL,
    CONSTRAINT fk_anunciante FOREIGN KEY (ID_ANUNCIANTE) REFERENCES ANUNCIANTES(ID)
);

CREATE TABLE CARRO_ACESSORIOS (
    ID SERIAL PRIMARY KEY,
    ID_CARRO INTEGER NOT NULL,
    CAMBIO VARCHAR(1),
    PORTAS INTEGER,
    AIR_BAG BOOLEAN,
    ALARME VARCHAR(1),
    AR_CONDICIONADO BOOLEAN,
    DIRECAO VARCHAR(1),
    FREIO_ABS BOOLEAN,
    TRAVAS VARCHAR(1),
    VIDROS VARCHAR(1),
    AR_QUENTE BOOLEAN,
    COMPUTADOR_BORDO BOOLEAN,
    DESEMBAÇADOR VARCHAR(1),
    TIPO_RODA VARCHAR(1),
    TETO_SOLAR BOOLEAN,
    TRACAO_4X4 BOOLEAN,
    CONSTRAINT fk_carro FOREIGN KEY (ID_CARRO) REFERENCES CARROS(ID)
);

CREATE TABLE ANUNCIOS (
    ID SERIAL PRIMARY KEY,
    DESCRICAO VARCHAR(100) NOT NULL,
    ID_ANUNCIANTE INTEGER NOT NULL,
    DATA_ANUNCIO DATE NOT NULL,
    ID_TIPOS_ANUNCIO INTEGER NOT NULL,
    ST_ATIVO BOOLEAN DEFAULT TRUE,
    ID_IMOVEL INTEGER,
    ID_CARRO INTEGER,
    CONSTRAINT fk_anunciante FOREIGN KEY (ID_ANUNCIANTE) REFERENCES ANUNCIANTES(ID),
    CONSTRAINT fk_tipos_anuncio FOREIGN KEY (ID_TIPOS_ANUNCIO) REFERENCES TIPOS_ANUNCIO(ID),
    CONSTRAINT fk_imovel FOREIGN KEY (ID_IMOVEL) REFERENCES IMOVEIS(ID),
    CONSTRAINT fk_carro FOREIGN KEY (ID_CARRO) REFERENCES CARROS(ID)
);

CREATE TABLE TIPOS_ANUNCIO (
    ID SERIAL PRIMARY KEY,
    CATEGORIA_ANUNCIO VARCHAR(1) NOT NULL,
    TIPO_ANUNCIO VARCHAR(1) NOT NULL,
    SALDO INTEGER,
    DESCRICAO VARCHAR(200),
    DIAS_DURACAO INTEGER,
    CONSTRAINT unq_categoria_anuncio UNIQUE (CATEGORIA_ANUNCIO),
    CONSTRAINT unq_tipo_anuncio UNIQUE (TIPO_ANUNCIO)
);

-- Adicionando comentários para documentação
COMMENT ON COLUMN TIPOS_ANUNCIO.CATEGORIA_ANUNCIO IS 'Categoria do anúncio: P-Preferencial; C-Comum';
COMMENT ON COLUMN TIPOS_ANUNCIO.TIPO_ANUNCIO IS 'Tipo do anúncio: I-Imóvel; C-Carro';
COMMENT ON COLUMN TIPOS_ANUNCIO.SALDO IS 'Saldo relacionado ao tipo de anúncio';
COMMENT ON COLUMN TIPOS_ANUNCIO.DESCRICAO IS 'Descrição do tipo de anúncio';
COMMENT ON COLUMN TIPOS_ANUNCIO.DIAS_DURACAO IS 'Duração do anúncio em dias';

CREATE TABLE AVALIACOES (
    ID SERIAL PRIMARY KEY,
    ID_ANUNCIANTE_AVALIADO INTEGER NOT NULL,
    DESCRICAO VARCHAR(200),
    RATING INTEGER CHECK (RATING BETWEEN 1 AND 5),
    ID_ANUNCIANTE_AVALIADOR INTEGER NOT NULL,
    FOREIGN KEY (ID_ANUNCIANTE_AVALIADO) REFERENCES ANUNCIANTES(ID),
    FOREIGN KEY (ID_ANUNCIANTE_AVALIADOR) REFERENCES ANUNCIANTES(ID)
);

CREATE TABLE IMOVEL_DETALHES (
    ID SERIAL PRIMARY KEY,
    ID_IMOVEL INTEGER NOT NULL,
    SUITES INTEGER,
    BANHEIROS INTEGER,
    GARAGEM INTEGER,
    SACADA INTEGER,
    COMODO INTEGER,
    SALA INTEGER,
    QUARTO INTEGER,
    FOREIGN KEY (ID_IMOVEL) REFERENCES IMOVEIS(ID)
);
